url: "https://USERNAME.github.io"
# the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/matt" # the subpath of your site, e.g. /blog
title: "Matt Ralston" # the name of your site, e.g. ACME Corp.

# sass: 
#   sass_dir: _sass

permalink: pretty

plugins: 
  - jekyll-paginate
  # - jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: '/tag/:name/'

paginate: 4
paginate_path: "/blog/page:num/"
# comments: true

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: matthewralston
 
# Page title
homepage: Home
portfolioPage: Portfolio
